//! Das Build-Skript dieser Einheit / the build script of this unit.
//!
//! Deutsch: Es läuft vor dem Übersetzen der Bibliothek, liest `daten/farben.txt`
//! und schreibt daraus eine Rust-Datei nach `OUT_DIR`. Die Bibliothek zieht
//! diese Datei mit `include!` herein.
//!
//! English: it runs before the library is compiled, reads `daten/farben.txt` and
//! writes a Rust file out of it into `OUT_DIR`. The library pulls that file in
//! with `include!`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Deutsch: Ohne diese Zeile läuft das Skript bei jeder Änderung an irgendeiner
    // Datei des Pakets erneut. Mit ihr läuft es nur, wenn die genannte Datei sich
    // ändert, und das ist der Grund, warum ein Bau danach schnell ist.
    // English: without this line the script runs again on every change to any file
    // of the package. With it, it runs only when the named file changes, and that
    // is why a build afterwards is fast.
    println!("cargo::rerun-if-changed=daten/farben.txt");

    let quelle = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .join("daten")
        .join("farben.txt");
    let text = fs::read_to_string(&quelle).expect("daten/farben.txt laesst sich lesen");

    let farben: Vec<&str> = text
        .lines()
        .map(str::trim)
        .filter(|z| !z.is_empty())
        .collect();

    let mut erzeugt = String::new();
    erzeugt.push_str("// Deutsch: Erzeugt von build.rs. Nicht von Hand aendern.\n");
    erzeugt.push_str("// English: generated by build.rs. Do not edit by hand.\n");
    erzeugt.push_str(&format!("pub const FARBEN: [&str; {}] = [\n", farben.len()));
    for farbe in &farben {
        erzeugt.push_str(&format!("    {farbe:?},\n"));
    }
    erzeugt.push_str("];\n");

    let ziel = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("farben.rs");
    fs::write(&ziel, erzeugt).expect("die erzeugte Datei laesst sich schreiben");
}
